name: MS Teams Notification

on:
  push:
    branches:
      - main

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to MS Teams
        uses: actions/checkout@v2
        with:
          webhook-url: https://o365kopo.webhook.office.com/webhookb2/bb297453-40c6-4dc2-b9bd-fda07688a327@ad21525c-fc0f-4dbc-a403-67ce00add0e4/IncomingWebhook/bb1c1e77ce144ebc860356c71b3dd22e/d65d978b-6555-40a1-84d0-6beb009925d8
          message: "GitHub에서 새로운 push 이벤트가 발생했습니다!"
